---
- name: Forcer le démarrage de Veyon (.103 et .105)
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Activer et démarrer le service veyon
      systemd:
        name: veyon
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Activer et démarrer le service (nom alternatif veyon-service)
      systemd:
        name: veyon-service
        state: started
        enabled: yes
      ignore_errors: yes
